routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');


Route::prefix('/documents')->name('documents.')->group(function () {

    Route::get('/', 'DocumentController@overview')->name('overview');
    Route::post('/', 'DocumentController@create')->name('create');
    Route::get('/{documentId}', 'DocumentController@show')->name('show');
    Route::put('/{documentId}', 'DocumentController@update')->name('update');
    Route::delete('/{documentId}', 'DocumentController@delete')->name('delete');
    Route::get('/{documentId}/edit', 'DocumentController@edit')->name('edit');

    Route::get('/{documentId}/editor', 'ImageEditorController@index')->name('editor');
});

Route::prefix('/images')->name('images.')->group(function () {

    Route::post('/', 'ImageController@upload')->name('upload');
    Route::patch('/{imageId}', 'ImageController@patch')->name('patch');
    Route::delete('/{imageId}', 'ImageController@delete')->name('delete');

});

Route::prefix('/api/v1')->name('api_v1.')->group(function () {

    Route::prefix('/documents')->name('documents.')->group(function () {

        Route::get('/{documentId}/images', 'ImageEditorController@getImages')->name('get_images');
        Route::post('/{documentId}/images', 'ImageEditorController@saveImages')->name('save_images');

    });

});

app/Document.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

/**
 * Class Document
 * @package App
 *
 * @property-read string $id
 * @property array $meta
 * @property string $userkey
 * @property \Illuminate\Support\Collection $imageFiles
 * @property string $created_at
 * @property string $updated_at
 */
class Document extends Eloquent
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'userkey', 'meta',
    ];

    protected $dates = [
        'created_at', 'updated_at',
    ];

    public function imageFiles()
    {
        return $this->embedsMany(ImageFile::class);
    }

    public function hasImageFiles()
    {
        return $this->imageFiles() ? true : false;
    }
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use App\Document;
use App\Http\Requests\CreateImageDocumentRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

/**
 * Class DocumentController
 * @package App\Http\Controllers
 */
class DocumentController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function overview()
    {
        $documents = Document::orderBy('created_at', 'desc')->get();
        return view('documents.overview', compact('documents'));
    }

    /**
     * @param \App\Http\Requests\CreateImageDocumentRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function create(CreateImageDocumentRequest $request): RedirectResponse
    {
        try {

            $userkey = $this->getUserKey();

            $doc = new Document;
            $doc->fill([
                'userkey' => $userkey,
            ]);
            $doc->save();

            /** @var \Illuminate\Http\UploadedFile[] $images */
            $images = $request->file('images');
            if (count($images) > 0) {
                $type = $request->request->get('type');
                foreach ($images as $image) {
                    if (!$image->isValid()) {
                        throw new \RuntimeException('File is invalid.');
                    }

                    $fileExtension = $image->extension();
                    $fileName = Str::uuid() . '.' . $fileExtension;
                    $image->storeAs('public/images', $fileName);

                    $doc->imageFiles()->create([
                        'userkey' => $userkey,
                        'name' => $fileName,
                        'type' => $type,
                    ]);
                }
            }

            return redirect(route('documents.show', ['documentId' => $doc->id]));

        } catch (\Exception $ex) {
            $this->handleException($ex);
            return redirect(route('index'));
        }
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param string                   $documentId
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|\Illuminate\View\View
     */
    public function show(Request $request, $documentId)
    {
        try {

            $doc = $this->apiHandler()->getDocumentUsingId($documentId);
            return view('documents.show', compact('doc'));

        } catch (\Exception $ex) {
            $this->handleException($ex);
            return redirect(route('documents.overview'));
        }
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param string                   $documentId
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|\Illuminate\View\View
     */
    public function edit(Request $request, $documentId)
    {
        try {

            $doc = $this->apiHandler()->getDocumentUsingId($documentId);
            return view('documents.edit', compact('doc'));

        } catch (\Exception $ex) {
            $this->handleException($ex);
            return redirect(route('documents.overview'));
        }
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param string                   $documentId
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $documentId)
    {
        try {

            $meta = $request->request->get('meta');

            $this->apiHandler()->updateDocumentUsingId($documentId, $meta);

            session()->flash('alert_type', 'success');
            session()->flash('alert_msg', 'Document successfully updated.');

        } catch (\Exception $ex) {
            $this->handleException($ex);
        }
        return redirect(route('documents.show', compact('documentId')));
    }

    /**
     * @param string $documentId
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function delete($documentId)
    {
        try {

            $doc = $this->apiHandler()->deleteDocumentUsingId($documentId);

            session()->flash('alert_type', 'success');
            session()->flash('alert_msg', 'Document successfully deleted.');

        } catch (\Exception $ex) {
            $this->handleException($ex);
        }
        return redirect(route('documents.overview'));
    }
}

resources/views/documents/edit.blade.php
@extends('layouts.default-container')

@push('page-styles')

@endpush

@section('container-content')
    <div class="mb-3">
        <h4>Edit Document {{ $doc->id }}</h4>
    </div>

    <div class="mb-3">
        <a href="{{ route('documents.show', ['documentId' => $doc->id]) }}"
           class="btn btn-default"
        >
            Cancel
        </a>
    </div>

    <div class="mb-3">
        <div class="card">
            <div class="card-body">
                <h5>Images</h5>
            </div>
            <div class="hslide">
                <div v-show="hasScrollHint" class="hslide__scroll-hint-right"></div>
                <div class="hslide__scroll-container">
                    <div class="hslide__list">
                        @foreach($doc->imageFiles as $imageFile)
                            <img src="{{ Storage::url('images/'.$imageFile->name) }}" class="img-thumbnail">
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mb-3">
        <div class="card">
            <div class="card-body">
                <h5>MetaData</h5>
                <div id="meta-form"
                     data-doc-id="{{ $doc->id }}"
                     data-form='@json($doc->meta)'
                ></div>
            </div>
        </div>
    </div>

@endsection

@push('page-scripts')
<script src="{{ mix('js/meta_form.js') }}"></script>
@endpush

resources/views/documents/editor.blade.php
@extends('layouts.app')

@push('page-styles')
@endpush

@section('page-content')
    <div class="mt-5">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    @include('components.navbar')
                    <div class="mb-3">
                        <h4>Editor {{ $doc->id }}</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="image-editor"
         data-doc-id="{{ $doc->id }}"
    ></div>



@endsection

@push('page-scripts')
<script src="{{ mix('js/image_editor.js') }}"></script>
@endpush

resources/views/documents/overview.blade.php
@extends('layouts.default-container')

@push('page-styles')
@endpush

@section('container-content')
    <div class="mb-3">
        <h4>Overview Documents</h4>
    </div>

    @if(count($documents) > 0)
        @foreach($documents as $doc)
            <div class="card mb-3">
                <div class="card-body p-2">
                    <div class="media">
                        @if(count($doc->imageFiles) > 0)
                            <div class="mr-2 product-image img-thumbnail" style="background-image: url('{{ Storage::url('images/'.$doc->imageFiles->first()->name) }}?v={{$doc->imageFiles->first()->created_at}}');"></div>
                        @else
                            <div class="mr-2 product-image img-thumbnail bg-default"></div>
                        @endif
                        <div class="media-body">
                            <div>
                                <a href="{{ route('documents.show', ['documentId' => $doc->id]) }}">
                                    {{ $doc->id }}
                                </a>
                            </div>
                            <div class="text-muted mb-2">
                                <small>Images: {{ count($doc->imageFiles) }}</small>
                                @foreach($doc->imageFiles as $imageFile)
                                    <span class="badge badge-secondary">{{ $imageFile->type }}</span>
                                @endforeach
                            </div>
                            <div>
                                <a href="{{ route('documents.edit', ['documentId' => $doc->id]) }}"
                                   class="btn btn-default btn-sm"
                                >
                                    <i class="far fa-edit"></i><span class="ml-2">Edit</span>
                                </a>
                                <a href="{{ route('documents.editor', ['documentId' => $doc->id]) }}"
                                   class="btn btn-default btn-sm"
                                >
                                    <i class="fas fa-tools"></i><span class="ml-2">Feature Editor</span>
                                </a>
                                @include('components.delete-document', ['btnSize' => 'sm', 'documentId' => $doc->id, 'formId' => 'deleteAction_'.$doc->id])
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    @else
        <div class="card">
            <div class="card-body m-5 text-center">
                <h5>No Documents Found</h5>
            </div>
        </div>
    @endif

@endsection

@push('page-scripts')
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            setEventListener(document.getElementsByClassName('deleteDocumentAction'), 'submit', deleteDocumentModal);
        });
    </script>
@endpush

resources/views/documents/show.blade.php
@extends('layouts.default-container')

@push('page-styles')
@endpush

@section('container-content')
    <div class="mb-3">
        <h4>Document {{ $doc->id }}</h4>
    </div>

    <div class="mb-3">
        <a href="{{ route('documents.edit', ['documentId' => $doc->id]) }}"
           class="btn btn-default"
        >
            <i class="far fa-edit"></i><span class="ml-2">Edit</span>
        </a>
        <a href="{{ route('documents.editor', ['documentId' => $doc->id]) }}"
           class="btn btn-default"
        >
            <i class="fas fa-tools"></i><span class="ml-2">Feature Editor</span>
        </a>
        @include('components.delete-document', ['documentId'=>$doc->id])
    </div>

    <div class="mb-3">
        <div class="card">
            <div class="card-body">
                <h5 class="m-0">Meta</h5>
            </div>
            @if(isset($doc->meta) && $doc->meta)
                <table class="table mb-0">
                    <tbody>
                    @foreach($doc->meta as $key => $val)
                        <tr>
                            <td><strong>{{ $key }}</strong></td>
                            <td>{{ $val }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <div class="card-body text-center p-5 border-top">
                    <h6>No MetaData Found</h6>
                </div>
            @endif
        </div>
    </div>

    <div class="mb-3">
        <div class="card" id="imageContainer">
            <div class="card-body">
                <h5 class="m-0">Images</h5>
            </div>
            @if(count($doc->imageFiles) > 0)
                @foreach($doc->imageFiles as $imageFile)
                    <div class="media border-top p-2 imgData" data-img-file-id="{{$imageFile->id}}">
                        <div class="mr-2 product-image" style="background-image: url('{{ Storage::url('images/'.$imageFile->name) }}?v={{ $imageFile->created_at }}');"></div>
                        <div class="media-body">
                            <div class="mb-2">
                                <p class="m-0">Name: {{$imageFile->name}}</p>
                                <p class="m-0">Type: <span class="badge badge-secondary">{{$imageFile->type}}</span></p>
                            </div>
                            <select name="typeSelect" class="imgTypeSelect form-control form-control-sm mb-2" value="{{ $imageFile->type }}">
                                @foreach(config('common.images.types') as $type)
                                    @if($type === $imageFile->type)
                                        <option value="{{ $type }}" selected>{{ __('images.types.'.$type) }}</option>
                                    @else
                                        <option value="{{ $type }}">{{ __('images.types.'.$type) }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @include('components.delete-image', ['btnSize' => 'sm', 'imageId' => $imageFile->id, 'formId' => 'deleteAction_'.$imageFile->id])
                        </div>
                    </div>
                @endforeach
            @else
                <div class="card-body text-center p-5 border-top">
                    <h6>No Images Found</h6>
                </div>
            @endif
            <div class="card-body border-top">
                <h5>Image Upload</h5>
                <form method="POST"
                      action="{{ route('images.upload') }}"
                      enctype="multipart/form-data"
                >
                    @method('POST')
                    @csrf
                    @include('components.image-upload-fields')
                    <input type="hidden" name="document_id" value="{{ $doc->id }}">
                    <button type="submit" class="btn btn-primary">Upload</button>
                </form>
            </div>
        </div>
    </div>

@endsection

@push('page-scripts')
<script>

    function updateImageType(id, type) {
        return axios.patch(`/images/${id}`, {type});
    }

    document.addEventListener('DOMContentLoaded', () => {
        setEventListener(document.getElementsByClassName('deleteDocumentAction'), 'submit', deleteDocumentModal);
        setEventListener(document.getElementsByClassName('deleteImageAction'), 'submit', deleteImageModal);
    });

    $('#imageContainer').on('change', '.imgTypeSelect', function (e) {
        e.preventDefault();
        let rootParent = $(this).parent().parent();
        let data = rootParent.data();

        const imgFileId = data.imgFileId;
        const imgFileType = this.value;

        console.log('action, imgTypeSelect',imgFileId, imgFileType);

        updateImageType(imgFileId, imgFileType)
            .then((response) =>{
                console.log(response.data.message);
                rootParent.find('span.badge.badge-secondary').text(imgFileType);
            })
            .catch((error) =>{
                console.log(error.response);
                rootParent.addClass('bg-danger');
            })
        ;
    });
</script>
@endpush